# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-11'

steps:
- task: CmdLine@2
  inputs:
    script: |
      pod deintegrate
      pod install --verbose
      #xcodebuild -sdk iphoneos -configuration Release -workspace "/Users/runner/work/1/s/ios-app-particle-setup.xcodeproj/project.xcworkspace" -scheme ios-app-particle-setup build CODE_SIGNING_ALLOWED=NO OTHER_LDFLAGS="-L\$(inherited) -L\$(PROJECT_DIR)/Pods" -verbose

    
- task: CmdLine@2
  inputs:
    script: |
      cd Pods
      ls
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'ios-app-particle-setup.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
