# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-11'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false

    
- task: CmdLine@2
  inputs:
    script: |
      cd Pods
      ls
      xcodebuild -sdk iphoneos -configuration Release -workspace /Users/runner/work/1/s/ios-app-particle-setup.xcworkspace -scheme ios-app-particle-setup build -verbose CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=Apple Distribution: Evince Development (NF47B74D2S) PROVISIONING_PROFILE=ff12cb3c-949a-4aba-97b0-2a92d2304b30 -verbose
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'ios-app-particle-setup.xcworkspace'
    scheme: 'ios-app-particle-setup'
    packageApp: false
    signingOption: 'manual'
    signingIdentity: 'Apple Distribution: Evince Development (NF47B74D2S)'
    provisioningProfileUuid: 'ff12cb3c-949a-4aba-97b0-2a92d2304b30'
    args: -verbose
    publishJUnitResults: true
